### ISSUE TITLE
Skip importing common resources but finish the import?

### ISSUE THREAD

**Issue by chenboy3** [magodo/tfmerge#3]
Hi, thanks for creating this tool! There's one edge case we're running when using this tool as part of a larger terraform import script - should the two statefiles share any resources in common, you'll get the following error:

```
resource {tf_resource} is defined in both state files terraform.tfstate and new.tfstate
```

Even if for example `terraform.state` contains resources `A, B` and `new.tfstate` contains resources `B, C`, ideally we'd want the import to still work such that `terraform.state` contains resources `A, B, C` after execution (skipping these resource defined errors)

**Comment by magodo** [comment]
Fixed in https://github.com/magodo/tfmerge/commit/cb78f836b8f81e260e37255fba3dd3e63b148e82
