### ISSUE TITLE
[Bug] Failed to obtain provider schema unavailable provider "registry.terraform.io/hashicorp/random"

### ISSUE THREAD

**Issue by arichtman-srt** [magodo/tfmerge#4]
# What versions are you using?

tfmerge: `cb78f836b8f81e260e37255fba3dd3e63b148e82`
environment: `Darwin bne-nb-ariel 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64 arm Darwin`

# What are you doing?

Attempting to merge state files.

# What was expected?

State files are merged and output file is populated with entire state.

# What happened?

```
$ tfmerge -o infra2.tfstate infra1.tfstate 02-base.json

Error: Failed to load plugin schemas

Error while loading schemas for plugin components: Failed to obtain provider
schema: Could not load the schema for provider
registry.terraform.io/hashicorp/random: failed to instantiate provider
"registry.terraform.io/hashicorp/random" to obtain schema: unavailable
provider "registry.terraform.io/hashicorp/random"..
```

# Anything else?

[Files to reproduce](https://gist.github.com/arichtman-srt/2ddf06c5e78ef97f244831f97132d058)

**Comment by magodo** [comment]
@arichtman-srt Can you try run `terraform init` beforehead?

**Comment by arichtman-srt** [comment]
I'm not in a terraform project - just trying to merge two state files.

**Comment by magodo** [comment]
@arichtman-srt I've tried your two state files in an un-init workspace, which succeeds:

```shell
/tmp/test2 via 💠 default took 4s
💤  tfmerge -o infra2.tfstate infra1.tfstate 02-base.json

/tmp/test2 via 💠 default took 4s
💤  tf version
Terraform v1.8.4
on linux_amd64

/tmp/test2 via 💠 default
💤  ls -a
.  ..  02-base.json  infra1.tfstate  infra2.tfstate
```

**Comment by arichtman-srt** [comment]
ok, thanks for looking anyway :)
